export HADOOP_HOME=/opt/hadoop_install/hadoop
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-i386

unalias fs &> /dev/null
alias fs="hadoop fs"
unalias hls &> /dev/null
alias hls="fs -ls"

export PATH+=:$HADOOP_HOME/bin
